apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: spring-kafka
build:
  artifacts:
    - image: docker.io/gamussa/javaz-spring-kafka
      context: .
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kubectl:
    manifests:
      - secret.yaml
      - deployment.yaml
